name: Generate Javadoc
on: [workflow_dispatch]

jobs:
  javadoc:
    name: Generate Javadoc
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¤ Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: ðŸ“š Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: 11
          architecture: x64

      - name: ðŸ“¦ Package with Maven
        run: mvn package -Dmaven.test.skip=true

      - name: ðŸš€ Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/*-javadoc.jar
          retention-days: 1
